apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "draino.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "draino.name" . }}
    helm.sh/chart: {{ include "draino.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "draino.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "draino.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /draino
          {{- if .Values.dryRun }}
            - --dry-run
          {{ end }}
          {{- range $key, $value := .Values.extraArgs }}
            - --{{ $key }}{{ if $value }}={{ $value }}{{ end }}
          {{- end }}
          {{- range .Values.conditions }}
            - {{ . }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 10002
              initialDelaySeconds: 30
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      serviceAccountName: {{ if .Values.rbac.create }}{{ template "draino.fullname" . }}{{ else }}"{{ .Values.rbac.serviceAccountName }}"{{ end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
