{{- if .Values.serviceMonitor.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: draino
  namespace: kube-system
  labels:
{{ include "draino.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 10002
      targetPort: 10002
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/name: {{ include "draino.name" . }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    prometheus: prometheus-operator
  name: {{ include "draino.name" . }}
  namespace: monitoring
spec:
  endpoints:
  - interval: 10s
    port: 10002
    path: /metrics
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "draino.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- end -}}