dryRun: false

extraArgs:
  evict-daemonset-pods:
  evict-emptydir-pods:

conditions:
  - NodeLocalDnsResolutionFailure

replicaCount: 1

image:
  repository: planetlabs/draino
  tag: 83b5f70
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

rbac:
  create: true
  serviceAccountName:

serviceMonitor:
  enabled: true # set to false to disable prometheus operator service monitor

nodeSelector: {}

tolerations: []

affinity: {}
